#!/bin/bash

# Intel license file (mandatory to use intel compilers)

export INTEL_LICENSE_FILE=/home/centos/intel_license/license.lic

# set-up intel compiler environment

. /home/centos/packages/esm.sh

# Number of core per node
export CESM_PES=16

sed -i -e "s/\$CESM_PES/$CESM_PES/g" /home/centos/.cime/config_machines.xml

cd /home/centos/packages/noresm-dev

sed -i.bak 's/# ARCHIVE COMMAND SIMILAR ACROSS ALL PLATFORMS/AR="$AR cq"/' cime/src/externals/mct/configure

cd cime/scripts

export casename='d16_intel2018.1_N1850_f19_tn14'

./create_newcase --case /home/centos/cases/$casename  --compset N1850 --res f19_tn14 --machine espresso_intel --run-unsupported

cd /home/centos/cases/$casename

NUMNODES=-2
./xmlchange --file env_mach_pes.xml --id NTASKS --val ${NUMNODES}
./xmlchange --file env_mach_pes.xml --id NTASKS_ESP --val 1
./xmlchange --file env_mach_pes.xml --id ROOTPE --val 0

./case.setup

# Customize run
cat >> user_nl_cam << EOF
nhtfrq(1) = -24
EOF

./xmlchange STOP_N=5
./xmlchange STOP_OPTION=ndays

# Build and run
./case.build
./case.submit

mkdir -p /home/centos/archive/cases

cp -R /home/centos/cases/$casename /home/centos/archive/cases/.
